### ISSUE TITLE
worker start needs to be added to diagram

### ISSUE THREAD

**Issue by pauljroy** [w3c/navigation-timing#128]
Hello, I'm on the Bing performance team.  Just was talking to Todd Reifsteck and we notice that Worker Start is not in the Navigation Timing diagram at the start of the processing model.  Would be great if it could be added.  Thanks!

**Comment by npm1** [comment]
@yoavweiss are you a good person to add this? I believe it goes after `unloadEventEnd` and before `redirectStart`.

**Comment by yoavweiss** [comment]
Sure

**Comment by nicjansma** [comment]
Is the value of `workerStart` is lost or wrong in some redirect scenarios?

e.g.

## Same Origin Redirects

When navigating to a.com which redirects to another page on a.com (all covered by a Service Worker):

1. Step (8) records `workerStart`
2. Step (9) starts the fetch for `a.com/`, which redirects to `a.com/redir`
3. Step (20e) sets all attributes to `0`, except a list which doesn't have `workerStart`
4. Step (20f) goes back to Step (9)

In this case, a.com's `workerStart` time is cleared at step (20e), and not re-set at any point.  Even though it's the same origin for the SW the whole time.  I think I would expect it to be saved to its original value (from the first fetch of `a.com/redir`, assuming the SW doesn't "restart" during the redirection).

## Cross-Origin Redirects

When navigating to a.com which redirects to b.com (both are covered by a Service Worker):

1. Step (8) records `workerStart` for a.com
2. Step (9) starts the fetch for `a.com/`, which redirects to `a.com/redir`
3. Step (20a) sets a few attributes to `0` (not including `workerStart`), then goes to Step (9)

In this case, a.com's `workerStart` time is saved though the rest of the DNS->Response attributes are for b.com.  I think I would expect the SW time to be for b.com instead of a.com here (unless there are privacy/security implications?).

I may be missing some security implications -- if the current steps are correct, we may want to note in the `workerStart` definition what it represents in redirect scenarios.

**Comment by nicjansma** [comment]
And some of this may be related to https://github.com/w3c/navigation-timing/issues/100

**Comment by nicjansma** [comment]
Addressed this (added to the diagram) and the comments above about the processing model in #131

**Comment by dashed** [comment]
I'm looking to calculate Service Worker initial boot times.

Is the following no longer reliable if `redirectStart > 0`?

```js
// measuring service worker startup time
let entry = performance.getEntriesByType('navigation')[0];
let swStartupTime = entry. fetchStart - entry.workerStart;
```

I've seen `requestStart - workerStart` referenced here https://webplatform.news/issues/2018-11-19 (and https://youtu.be/25aCD5XL1Jk?t=274 ). Unsure if this is better.

**Comment by nicjansma** [comment]
Correct, today if there are redirects, Service Worker Startup time (as `fetchStart-workerStart`) will include those redirect durations.

`requestStart-workerStart` would have the same issue.

**Comment by nicjansma** [comment]
This PR will be re-worked after discussions from the March 18th 2021 discussion with ServiceWorker folks:

https://w3c.github.io/web-performance/meetings/2021/2021-03-18/index.html

Notably:
* workerStart will only be reflective of the _last_ document, not the "_first document of the last same-origin redirect chain_".

**Comment by noamr** [comment]
It's now in the diagram.
