### ISSUE TITLE
Add non-normative explanations for each of the attributes and when they are set or unset

### ISSUE THREAD

**Issue by npm1** [w3c/navigation-timing#157]
Now that there is better integration with Fetch and HTML, it seems harder to understand what is going on by just looking at the Navigation Timing spec. Perhaps we should add some explanations either in the spec itself or in a separate explainer file where it is clear what the attributes are, when they should be set, etc.

It may also be beneficial to link the callers of the main methods, like the one to create a navigation timing entry. In particular, the HTML spec is hard to search (and that's assuming you know it is called from that spec, and not others like DOM or Fetch). The problem with this is that it may be harder to keep up to date.

**Comment by noamr** [comment]
I'm wondering if non-normative explanations is the way to go here, or we should find a mechanism where `w3c` specs can automatically find references in `whatwg` specs. Otherwise those links and explanations can become stale. Maybe a combination of both? Not sure if trying to link w3c/whatwg like this is a can of worms, or if we were planning to move some of these specs to whatg (?)

**Comment by yoavweiss** [comment]
Linking across orgs seems fine, but I agree about staleness concerns.

/cc @marcoscaceres who may have ideas on relevant tooling that can help.
