### ISSUE TITLE
Report that Critical-CH was used to restart a navigation

### ISSUE THREAD

**Issue by yoavweiss** [w3c/navigation-timing#177]
Chromium recently [got a report](https://bugs.chromium.org/p/chromium/issues/detail?id=1317666) that it's hard for folks deploying [Critical-CH](https://github.com/WICG/client-hints-infrastructure/blob/main/reliability.md#critical-ch) as a backup mechanism to [ACCEPT_CH](https://github.com/WICG/client-hints-infrastructure/blob/main/reliability.md#accept_ch) frames to know if/when that backup was actually used, and triggered a restart of the navigation (which is likely to result in user-visible delay)

It may make sense for us to report that as part of navigation timing. This somehow connects to other "types" of navigations that we're considering reporting, so it may make sense to find an API shape that doesn't require a separate attribute per type.

**Comment by nicjansma** [comment]
Discussed on Apr 28 WebPerf WG call: https://w3c.github.io/web-performance/meetings/2022/2022-04-28/index.html

**Comment by nicjansma** [comment]
From my testing, it looks like a `Critical-CH`-restarted navigation (in Chrome today) extends the `requestStart` to `responseStart` timestamps.

In other words, if the server takes +1 second to respond to the _second_ request for the navigated resource (having restarted because a `Critical-CH` requested a hint that wasn't sent on the first request), `responseStart` will be at least 1 second after `requestStart`.

As we approach wider deployments of Client Hints for Chrome and the User-Agent Reduction timeline, I'd like to see if we can get this information into NavigationTiming.  RUM providers could capture this information to help inform their customers about how effective UACH/UAR deployments and changes are, and to highlight any potentially costly restarted-navigations from Critical-CH.

A boolean flag for a Critical-CH-restarted request seems the easiest to implement.

I'm not sure if there are any other impacts from UACH/UAR that we'd want to measure/report on, so pondering that 🤔

**Comment by yoavweiss** [comment]
^^ @arichiv @miketaylr

**Comment by miketaylr** [comment]
I can see how this could be useful. WDYT, @arichiv?
