### ISSUE TITLE
click/touch events start time.

### ISSUE THREAD

**Issue by hiroshik850223** [w3c/navigation-timing#19]
For real-world navigation processing, hyper link is able to handle JavaScript click/touch events. But latest Processing Model doesn't suppose that use case.

See this sample. http://furoshiki.github.io/sample/perf02/index.html

This example navigation spends more than 1 second, but nav-timing API (also nav-timing 2) can't audit it.

**Comment by igrigorik** [comment]
This is a question about "time origin" defined in hr-time, see: http://w3c.github.io/hr-time/#time-origin-1

Note that as per above definition, the behavior is intentional. The part about confirmation dialogue is relatively new, and even there we start counting from the moment the user confirms the navigation.

As such, I believe this is a _wontfix_. 

/cc @plehegar @toddreifsteck

**Comment by plehegar** [comment]
I'd agree it's a wontfix. Even if you were able to audit the delay, there would be nothing that the developer can do without modifying the origin of the delay itself. And once you reached that conclusion, you can also conclude that you can monitor the delay in the origin, even if you cannot do it as part of the navigation.

**Comment by toddreifsteck** [comment]
I also agree with the Won't Fix.

Navigation Timing is designed to measure the lifecycle from navigationStart as defined at start of a page to end of navigation. (Aka.. the parts within control of that page's author) The previous page's author is responsible for all delays in navigation. As @plehegar states, it is possible for the previous page's author to measure and report delays in the click/onbeforeunload/onunload events without needing Navigation Timing.

**Comment by hiroshik850223** [comment]
Thank you for your clarification.
