### ISSUE TITLE
Is the merge of PerformanceTiming and PerformanceNavigation into PerformanceNavigationTiming web compatible?

### ISSUE THREAD

**Issue by foolip** [w3c/navigation-timing#22]
Continuing from https://github.com/w3c/performance-timeline/issues/32#issuecomment-119608461

In some ad-hoc testing it looks like `Performance.timing` and `Performance.navigation` are widely implemented, is the hope that those be removed from browser or should both forms of the API be supported at the same time?

**Comment by igrigorik** [comment]
Today, only IE correctly returns an array with a single resource when using `performance.getEntriesByType("navigation")`. As such, developers have to rely on `performance.timing` to get navigation timing data, and I think we'd cause quiet a bit of pain if we were to break that. I think we should offer it, but put a warning/disclaimer to nudge them towards getEntriesByType -- the latter is preferred since it allows us to return multiple entries and surface redirects.

I'm guessing we might have to do the same for Performance.navigation.

**Comment by foolip** [comment]
Does there need to be two different APIs for this, are `Performance.timing` and `Performance.navigation` that broken?

**Comment by igrigorik** [comment]
It's not that they're broken. Rather, they're not sufficient and we can't update their definition without breaking existing code. Both implicitly point at the "last request" in the navigation chain, which means we can't surface redirects (an often cited issue against NT1). 

If we were to design this stuff from scratch, we'd probably just point people towards performance.getEntriesByType("navigation"), which would return an array (no redirects is an array with single entry). As such, I think we'll need to keep existing definitions (not great, but that that ship has sailed), and offer a better implementation via getEntriesByType.

**Comment by foolip** [comment]
Thanks for explaining. Two APIs is unfortunate, but hopefully the `timing` and `navigation` attributes could be defined in terms of the new API. I'll leave this issue open to track defining that in the new spec, does that sound right?

**Comment by igrigorik** [comment]
yep, sgtm

**Comment by plehegar** [comment]
Here is the summary of the situation as I see it:
1- When we moved from milliseconds to sub-milliseconds, we came up with the DOMHighResTimeStamp type. [1]. As a consequence, we moved from unsigned long long (used in nav-timing 1) to double (used by all perf timeline entries). We figured out at the time that changing the type would break deployed apps.
2- We also changed the time origin:
 * in nav-timing-1, time origin is measured in milliseconds since midnight of January 1, 1970 (UTC).
 * in nav-timing-2, it's based on the time origin of HRT2, ie measured against the time of starting the navigation.

With the recent interfaces reshuffling, it became more apparent that we abandoned nav-timing-1 because the two versions don't make sense within the same context. We have:

nav-timing-1 defines:
[
interface Performance {
  readonly attribute PerformanceTiming timing;
  readonly attribute PerformanceNavigation navigation;
};

partial interface Window {
  [Replaceable] readonly attribute Performance performance;
};
]

while hr-time-2 defines:
[
[Exposed=(Window,Worker)]
interface Performance : EventTarget {
    DOMHighResTimeStamp now ();
    DOMHighResTimeStamp translateTime (DOMHighResTimeStamp time, (Window or Worker or SharedWorker or ServiceWorker) timeSource);
};

[NoInterfaceObject, Exposed=(Window,Worker)]
interface GlobalPerformance {
    [Replaceable]
    readonly    attribute Performance performance;
};
]

We don't want to expose the timing and navigation attributes to workers, so we can't simply do in nav-timing-2:
partial interface Performance {
  readonly attribute PerformanceTiming timing;
  readonly attribute PerformanceNavigation navigation;
}

Ideas?

[1] http://w3c.github.io/hr-time/#dom-domhighrestimestamp
[2] http://w3c.github.io/hr-time/#time-origin

**Comment by foolip** [comment]
If the `timing` and `navigation` attributes are only for compatibility and don't provide any important information, then simply not exposing them in workers by using `[Exposed=Window]` would do that. This is from [Gecko's Web IDL](https://github.com/mozilla/gecko-dev/blob/6a2a4a1aa9d8b3d2d6f623a88ffddf39e2ce304f/dom/webidl/Performance.webidl#L22):
```WebIDL
[Exposed=Window]
partial interface Performance {
  [Constant]
  readonly attribute PerformanceTiming timing;
  [Constant]
  readonly attribute PerformanceNavigation navigation;

  jsonifier;
};
```

Not sure what `jsonifier` is for, but with `[SameObject]` instead of `[Constant]` I think you could basically paste that into the spec.

**Comment by foolip** [comment]
CC @bzbarsky on `jsonifier` issue.

**Comment by plehegar** [comment]
Looking at the definition of Exposed in WebIDL, I wonder if something like that would be better (or is it equivalent?):
[[
```WebIDL
partial interface Performance {
  [Exposed=(Window)]
  readonly attribute PerformanceTiming timing;
  [Exposed=(Window)]
  readonly attribute PerformanceNavigation navigation;
};
```
]]

**Comment by bzbarsky** [comment]
> CC @bzbarsky on jsonifier issue.

`jsonifier` in Gecko's IDL is the same as what `serializer = { attribute }` (or `serializer = { inherit, attribute }` for an interface that inherits from another interface) is in the current Web IDL draft.  We don't implement the full proposed Web IDL serializer syntax for various reasons (e.g. I think it's overengineered and should be simplified).

In any case, the point of that is to make `JSON.stringify{performance)` do something sane.  Note that this is a longstanding issue in the webperf specs; first reported at https://lists.w3.org/Archives/Public/public-web-perf/2012Jun/0003.html 3 years or so ago, and poked at a few times since, but one that doesn't seem to be addressed in the latest draft I see at https://w3c.github.io/hr-time/#the-performance-interface

For the rest:

1. `[Constant]` is something we added in Gecko before `[SameObject]` existed in IDL.  They're just aliases for each other in our codegen, more or less; definitely the same in this case.  Would be happy to update our IDL if the spec ends up with `[SameObject]` here.
2. The exposure set of an interface member without explicit `[Exposed]` specified is, per spec, "the exposure set of the interface or partial interface the member is declared on".  So having `[Exposed]` on a partial interface is exactly the same as putting that exact `[Exposed]` value on all the members that don't have other `[Exposed]` annotations already.  So what's in https://github.com/w3c/navigation-timing/issues/22#issuecomment-121772709 is equivalent to Gecko's IDL in terms of exposure sets.

**Comment by toddreifsteck** [comment]
I believe the following will generally address the following issues:
1. Add timing/navigation only on Window to ensure spec reflects Interopable web
2. Add toJson() to performance object

It leaves open the issue that PerformanceNavigation at performance.navigation uses unsigned long and does not use same time origin as performance.getEntriesByType("navigation"). The only fix I currently see for that issue is pulling the nav timing 1 spec forward into nav timing 2 and having them both defined. **Any other ideas?**

partial interface Performance {
  [Exposed=(Window), SameObject]
  readonly attribute PerformanceTiming timing;
  [Exposed=(Window), SameObject]
  readonly attribute PerformanceNavigation navigation;

  serializer;
};

**Comment by bzbarsky** [comment]
You don't need the parens around "Window", by the way.  Just `Exposed=Window` works.

And you need `serializer = { attribute }`.

**Comment by toddreifsteck** [comment]
partial interface Performance {
 [Exposed=Window, SameObject]
 readonly attribute PerformanceTiming timing;
 [Exposed=Window, SameObject]
 readonly attribute PerformanceNavigation navigation;

serializer = {timing, navigation};
 };

**Comment by bzbarsky** [comment]
No, I really did mean `serializer = { attribute }`, which will serialize all the serializable attributes (e.g. the `memory` attribute if that ever gets standardized).

**Comment by foolip** [comment]
In other words:
```WebIDL
[Exposed=Window]
partial interface Performance {
  [SameObject] readonly attribute PerformanceTiming timing;
  [SameObject] readonly attribute PerformanceNavigation navigation;
  serializer = { attribute };
};
```

**Comment by foolip** [comment]
> It leaves open the issue that PerformanceNavigation at performance.navigation uses unsigned long and does not use same time origin as performance.getEntriesByType("navigation"). The only fix I currently see for that issue is pulling the nav timing 1 spec forward into nav timing 2 and having them both defined.

What kind of bugs should one expect if one tries to simply use the same time type and origin as the newer API? If it's extremely corner-casey one could attempt to just align them, but the risk would really have to be small, at least if those corner cases are already interoperably implemented.

**Comment by toddreifsteck** [comment]
I believe we need to define it as follows to allow all other extensions to the interface to be exposed to Workers by default.

[Exposed=Window, Worker]
partial interface Performance {
  [Exposed=Window, SameObject] readonly attribute PerformanceTiming timing;
  [Exposed=Window, SameObject] readonly attribute PerformanceNavigation navigation;
  serializer = { attribute };
};

The reason why just changing the type and origin will cause breaks on the net can be seen below----
performance.timing has the following shape:
{
   connectEnd: 1437038143662,
   connectStart: 1437038143662,
   domainLookupEnd: 1437038143662,
   domainLookupStart: 1437038143662,
   domComplete: 1437038143771,
   domContentLoadedEventEnd: 1437038143771,
   domContentLoadedEventStart: 1437038143771,
   domInteractive: 1437038143771,
   domLoading: 1437038143732,
   fetchStart: 1437038143662,
   loadEventEnd: 1437038143777,
   loadEventStart: 1437038143773,
   msFirstPaint: 1437038143778,
   navigationStart: 1437038143662,
   redirectEnd: 0,
   redirectStart: 0,
   requestStart: 1437038143688,
   responseEnd: 1437038143747,
   responseStart: 1437038143732,
   unloadEventEnd: 0,
   unloadEventStart: 0
}

performance.getEntriesByType("navigation") has the following shape:
{
   connectEnd: 0.2932921750595071,
   connectStart: 0.2932921750595071,
   domainLookupEnd: 0.2932921750595071,
   domainLookupStart: 0.2932921750595071,
   domComplete: 109.80456398940517,
   domContentLoadedEventEnd: 109.2870592229139,
   domContentLoadedEventStart: 109.2870592229139,
   domInteractive: 109.27995389431218,
   domLoading: 70.73038830620808,
   duration: 115.30685151047444,
   entryType: "navigation",
   fetchStart: 0.2932921750595071,
   loadEventEnd: 115.30685151047444,
   loadEventStart: 111.18576092148217,
   name: "document",
   navigationStart: 0,
   redirectCount: 0,
   redirectEnd: 0,
   redirectStart: 0,
   requestStart: 26.34300579084281,
   responseEnd: 85.04249381244301,
   responseStart: 70.73038830620808,
   startTime: 0,
   type: "navigate",
   unloadEventEnd: 0,
   unloadEventStart: 0
}

**Comment by foolip** [comment]
> I believe we need to define it as follows to allow all other extensions to the interface to be exposed to Workers by default

Which other extensions? `Exposed` on a partial interface only applies to the things in that same partial interface, so unless the implicit assumption is that this would be merged with an existing partial interface it's equivalent.

**Comment by toddreifsteck** [comment]
Interesting. I misread http://heycam.github.io/webidl/#Exposed and thought it bled across the interface. Thanks for correcting. Opened user-timing issue on the missing Exposed.

**Comment by bzbarsky** [comment]
The IDL in https://github.com/w3c/navigation-timing/issues/22#issuecomment-121876069 would make the serializer only be exposed in window.  That's probably fine for now, since all the things that are interesting to serialize would also only be exposed in window, but if we think we'll add things later in workers that need serializing we might as well put the serializer both places right now.

The IDL in https://github.com/w3c/navigation-timing/issues/22#issuecomment-121899284 doesn't need the `[Exposed=(Window,Worker)]` on the partial interface itself; the default exposure set of a partial interface is the exposure set of the main interface, which is already `(Window,Worker)` for `Performance`.

**Comment by foolip** [comment]
Uh, right, I suppose it would make more sense to just move `serializer = { attribute }` to the main definition of the interface?

**Comment by bzbarsky** [comment]
That would make sense to me, yes.

**Comment by plehegar** [comment]
This should be resolved now. Please reopen if you believe otherwise.
