### ISSUE TITLE
Relationship between performance.timing.navigationStart and hr-time time origin

### ISSUE THREAD

**Issue by majido** [w3c/navigation-timing#43]
Based on my reading of the spec [performance.timing.navigationStart](https://www.w3.org/TR/navigation-timing-2/#widl-PerformanceTiming-navigationStar) seems to be the same as [time origin](https://w3c.github.io/hr-time/#time-origin) as specified in hr-time spec. The wording is not exactly the same so I may be mistaken.

If my interpretation is correct then I think we should spell this relationship explicitly in this spec and perhaps align the texts. Otherwise, I think they should be made the same. :)
## hr-spec definition

If the global object [HTML51] is a Window object, the time origin must be equal to:
- the time when the browsing context is first created if there is no previous document;
- otherwise, the time of the user confirming the navigation if a confirmation dialog is displayed during the prompt to unload algorithm;
- otherwise, the time of starting the navigation responsible for loading the Window object's newest Document object.
## navigation-timing-2 definition

This attribute must return the time immediately after the user agent finishes prompting to unload the previous document. If there is no previous document, this attribute must return the time the current document is created.

where 
current document = Window object's newest Document object.

**Comment by igrigorik** [comment]
Hmm, conceptually, yes.. Only gotcha is that `PerformanceTiming` is a legacy interface which predates our time origin definition in HR-Time. That said, I guess we're not planning to deprecate it, and since it's pretty much aligned, perhaps we can simplify it. 

> navigationStart
>> This attribute must return the [time origin](http://w3c.github.io/hr-time/#time-origin) of the `Window` object.

@plehegar @toddreifsteck wdyt?

**Comment by toddreifsteck** [comment]
I agree with @igrigorik 's suggestion.

**Comment by plehegar** [comment]
performance.timing.navigationStart is part of the historical section of the spec. That section starts with: "All time values defined in this appendix are measured in milliseconds since midnight of January 1, 1970 (UTC)."

Thus the description says "If there is no previous document, this attribute must return the time the current document is created."

Note that the equivalent in PerformanceNavigationTiming is the startTime, which is always equal to 0:
  https://w3c.github.io/navigation-timing/#dom-PerformanceNavigationTiming-startTime

We should do better at marking that section as historical. Folks shouldn't look at the historical if they're looking at using the L2 but we still need to keep it there for legacy.

**Comment by plehegar** [comment]
See https://www.w3.org/2016/05/04-webperf-minutes.html#item05

**Comment by igrigorik** [comment]
Here's my attempt..

![image](https://cloud.githubusercontent.com/assets/10652/18668427/41cfa686-7f2d-11e6-9440-4824ebb95563.png)


```
#historical {
    background-position: right;
    background-repeat: repeat-y;
    background-color: rgba(251, 233, 233, 0.5);
    background-image:url("data:image/svg+xml;utf8,<svg xmlns='http://www.w3.org/2000/svg' version='1.1' height='150px' width='50px'><text x='0' y='50' fill='red' font-size='30' fill-opacity='0.20'>L1</text></svg>");
}
```

@plehegar @toddreifsteck any objections?

**Comment by plehegar** [comment]
belated +1 on this one. Nice result!
