### ISSUE TITLE
Processing Model chart is missing domLoading marker

### ISSUE THREAD

**Issue by andydavies** [w3c/navigation-timing#44]
Processing model chart - https://w3c.github.io/navigation-timing/#processing-model - is missing a marker for domLoading.

**Comment by igrigorik** [comment]
@plehegar we have https://github.com/w3c/navigation-timing/blob/gh-pages/timing-overview.png checked in, which reflects all the right marks, but we have an SVG in the spec. Any objections to linking to the PNG? Do we have a doc / source for the png? Is that the PPT?

**Comment by igrigorik** [comment]
Also missing: workerStart.

**Comment by plehegar** [comment]
No objection from me. The original drawing was indeed the PPT.

**Comment by igrigorik** [comment]
I'm proposing we update NT with the following:

![image](https://cloud.githubusercontent.com/assets/10652/20411770/c952649a-acd7-11e6-89f4-db4b924494ac.png)

- domLoading is part of NT1 and we [deprecated it in NT2](https://w3c.github.io/navigation-timing/#widl-PerformanceTiming-domLoading), hence that's a no-op.
- Instead of replicating all of the RT timestamps, I propose we defer those to ResourceTiming (which includes workerStart)

The above would cleanly reflect what we define for [PerformanceNavigationTiming](https://w3c.github.io/navigation-timing/#idl-def-performancenavigationtiming) and keeps things tidy between specs -- e.g. if we update RT, we don't have to duplicate diagram changes to NT.

@plehegar @toddreifsteck any objections?

**Comment by yoavweiss** [comment]
SGTM. Maybe also add a link to the corresponding RT diagram?

**Comment by igrigorik** [comment]
Yeah, that one also needs to be updated and we can add a link to it in the figure caption.

**Comment by igrigorik** [comment]
While working on updating the RT diagram... here's another variant with RT visible:

![image](https://cloud.githubusercontent.com/assets/10652/20493791/11f6d060-afcf-11e6-81c5-44ee8146f395.png)

@toddreifsteck @plehegar any preference for one vs the other?

**Comment by toddreifsteck** [comment]
I, personally, like the 2nd one. I recommend labelling the Resource Timings section by connecting the sections with a line wrapping both ends going down then joining on a Resource Timings label to make it clear. But... just my opinion. :-) @nolanlawson

**Comment by plehegar** [comment]
I like the 2nd one but it duplicates information with RT. We'll get it out of sync at some point in the future,...

**Comment by igrigorik** [comment]
@plehegar in https://github.com/w3c/navigation-timing/pull/52 I link to the source (in an HTML comment), which contains both diagrams.. Arguably, when they're in the same doc, it's easier to remember to keep them in sync. That said, I can be convinced either way. 

@toddreifsteck I'll let you decide this one :) If you like #52, merge it. Otherwise, I can update it with the first diagram.
